import { Operaio } from '../interfaces/operai';

export let lista_operai: Operaio[] = [
  {
    id: '1',
    nome: 'Nikola Tesla',
    contratto: 'Indeterminato',
    mansione: 'EDILE',
    assicurazione: '12/31/2023',
    scadenze_contratto: ['12/31/2023'],
    qualifica: 'Ingegnere elettrico',
    visita_medica: '12/31/2023',
  },
  {
    id: '2',
    nome: 'Andrè Ampère',
    contratto: 'Indeterminato',
    mansione: 'EDILE',
    assicurazione: '12/31/2023',
    scadenze_contratto: ['12/31/2023'],
    qualifica: 'Fisico',
    visita_medica: '12/31/2023',
  },
  {
    id: '3',
    nome: 'Gustave de Coriolis',
    contratto: 'Indeterminato',
    mansione: 'EDILE',
    assicurazione: '12/31/2023',
    scadenze_contratto: ['12/31/2023'],
    qualifica: 'Fisico',
    visita_medica: '12/31/2023',
  },
  {
    id: '4',
    nome: 'Isaac Newton',
    contratto: 'Indeterminato',
    mansione: 'EDILE',
    assicurazione: '12/31/2023',
    scadenze_contratto: ['12/31/2023'],
    qualifica: 'Fisico',
    visita_medica: '12/31/2023',
  },
  {
    id: '5',
    nome: 'Michael Faraday',
    contratto: 'Stage',
    mansione: 'EDILE',
    assicurazione: '12/31/2023',
    scadenze_contratto: ['12/31/2023'],
    qualifica: 'Fisico',
    visita_medica: '12/31/2023',
  },
  {
    id: '6',
    nome: 'Carl Gauss',
    contratto: 'Indeterminato',
    mansione: 'EDILE',
    assicurazione: '12/31/2023',
    scadenze_contratto: ['12/31/2023'],
    qualifica: 'Matematico',
    visita_medica: '12/31/2023',
  },
];

export const OperaioTableHeaders: string[] = [
  'Info',
  'Nome',
  'Contratto',
  'Mansione',
  'Qualifica',
];
